/**
 * @fileoverview gRPC-Web generated client stub for armortal.protobuffed.example
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.30.1
// source: example.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_api_annotations_pb = require('./google/api/annotations_pb.js')
const proto = {};
proto.armortal = {};
proto.armortal.protobuffed = {};
proto.armortal.protobuffed.example = require('./example_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.armortal.protobuffed.example.AuthClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.armortal.protobuffed.example.AuthPromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.armortal.protobuffed.example.SignInRequest,
 *   !proto.armortal.protobuffed.example.SignInResponse>}
 */
const methodDescriptor_Auth_SignIn = new grpc.web.MethodDescriptor(
  '/armortal.protobuffed.example.Auth/SignIn',
  grpc.web.MethodType.UNARY,
  proto.armortal.protobuffed.example.SignInRequest,
  proto.armortal.protobuffed.example.SignInResponse,
  /**
   * @param {!proto.armortal.protobuffed.example.SignInRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.armortal.protobuffed.example.SignInResponse.deserializeBinary
);


/**
 * @param {!proto.armortal.protobuffed.example.SignInRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.armortal.protobuffed.example.SignInResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.armortal.protobuffed.example.SignInResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.armortal.protobuffed.example.AuthClient.prototype.signIn =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/armortal.protobuffed.example.Auth/SignIn',
      request,
      metadata || {},
      methodDescriptor_Auth_SignIn,
      callback);
};


/**
 * @param {!proto.armortal.protobuffed.example.SignInRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.armortal.protobuffed.example.SignInResponse>}
 *     Promise that resolves to the response
 */
proto.armortal.protobuffed.example.AuthPromiseClient.prototype.signIn =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/armortal.protobuffed.example.Auth/SignIn',
      request,
      metadata || {},
      methodDescriptor_Auth_SignIn);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.armortal.protobuffed.example.SignUpRequest,
 *   !proto.armortal.protobuffed.example.SignUpResponse>}
 */
const methodDescriptor_Auth_SignUp = new grpc.web.MethodDescriptor(
  '/armortal.protobuffed.example.Auth/SignUp',
  grpc.web.MethodType.UNARY,
  proto.armortal.protobuffed.example.SignUpRequest,
  proto.armortal.protobuffed.example.SignUpResponse,
  /**
   * @param {!proto.armortal.protobuffed.example.SignUpRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.armortal.protobuffed.example.SignUpResponse.deserializeBinary
);


/**
 * @param {!proto.armortal.protobuffed.example.SignUpRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.armortal.protobuffed.example.SignUpResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.armortal.protobuffed.example.SignUpResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.armortal.protobuffed.example.AuthClient.prototype.signUp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/armortal.protobuffed.example.Auth/SignUp',
      request,
      metadata || {},
      methodDescriptor_Auth_SignUp,
      callback);
};


/**
 * @param {!proto.armortal.protobuffed.example.SignUpRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.armortal.protobuffed.example.SignUpResponse>}
 *     Promise that resolves to the response
 */
proto.armortal.protobuffed.example.AuthPromiseClient.prototype.signUp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/armortal.protobuffed.example.Auth/SignUp',
      request,
      metadata || {},
      methodDescriptor_Auth_SignUp);
};


module.exports = proto.armortal.protobuffed.example;

