name: test

on: 
  push:
    branches: [ main ]
    
  workflow_dispatch:
    branches: [ main ]
        
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
        -   name: Checkout
            uses: actions/checkout@v2

        -   uses: actions/setup-go@v3
            with:
                go-version: '^1.19.0'
        
        -   run: go test -v ./...
